[package]
name = "silk-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
libc = "0.2"
thiserror = "1.0"

[build-dependencies]
bindgen = "0.53.1"
cc = "1.0"